[package]
name = "libgost"
version = "0.1.3"
entrypoint = "lib/libgost.typ"
authors = ["lipkin.gregory@yandex.ru"]
license = "MIT"
description = "Follow GOST 7.32-2017"
categories = ["paper", "thesis"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
